version: '3.8'

services:
  devops-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/devops-app
    working_dir: /devops-app
    command: python3 src/routes.py
    ports: 
      - 3000:3000